### ISSUE TITLE
Navbar color definition

### ISSUE THREAD

**Issue by kodl** [mcasimir/mobile-angular-ui#126]
in file navbar.less is defined 

``` css
 .btn-navbar, .btn {
    background: none;
    border: none;
    line-height: @navbar-app-height;
    padding-top: 0;
    padding-bottom: 0;
    color: @link-color;
    text-transform: uppercase;
    &:hover {
      color: @link-color;
    }
  }
```

I beleive, that it should be

``` css
color: @navbar-default-link-color;
```

instead of 

``` css
color: @link-color;
```
