### ISSUE TITLE
creating a loader - center on a view

### ISSUE THREAD

**Issue by napcat** [mcasimir/mobile-angular-ui#199]
I'm starting to build a new mobile app with this framework.
It will be my third application using angularjs, but my first using this framework. So far, so good! 
Thank you for excellent work! ;)

If I understood correctly I have a "content-app" and a "section" css class.
What should I use as my basic holder for the views?

I'm currently using section and trying to create a generic loader animation, that will be active and only removed when the view is ready. 

The problem is, I'm trying to center it vertically and horizontally.
Is there's any built in css helper to center a div inside a view?

**Comment by mcasimir** [comment]
Hi, there is no such helper, although I may think to add some in future, but you can browse demo to see how a similar effect is achieved.

Container should be `.app-content`, sections won't fill the screen vertically.

If you know width and height of loader I think the faster way would be to setup you own css:

``` css
.loader {
  display: block;
  position: absolute;
  top: 50%;
  left: 50%;
  width: 30px;
  height: 30px;
  margin-top: -15px;
  margin-left: -15px;
}
```
