### ISSUE TITLE
Having sidebar-left to also be toggleable

### ISSUE THREAD

**Issue by andrejkaurin** [mcasimir/mobile-angular-ui#210]
In previous version it was `toggleable deafult="inactive"`but this doen't work now in 1.0.3.
How to achieve to have left sidebar also closed and toggled by ui-toggle?

**Comment by ciromattia** [comment]
You only need to add
```
<div ui-toggle="uiSidebarLeft" class="btn pull-left sidebar-toggle">
<i class="fa fa-bars"></i>
</div>
```
at least in 1.2.0-beta11

**Comment by andrejkaurin** [comment]
That didn't help :-(
sidebar-right has that behavior by default but just can't make sidebar-left to work that way.

**Comment by ciromattia** [comment]
Can't understand, in the demo (master branch) both sidebars have the same behaviour, which one are you referring to?

**Comment by andrejkaurin** [comment]
Please see this screen
http://prntscr.com/5xssnt

**Comment by ciromattia** [comment]
Oh, in desktop mode.
Well, it sounds quite like an hack because the sidebar behavior is hardcoded in the styles, so you have to mangle it with a bit of LESS:
```less
@media (min-width: @screen-desktop) {
    .has-sidebar-left .app {
        margin-left: 0;
    }
    .sidebar-left-in .app {
        margin-left: @sidebar-left-width-lg;
    }
}
```
or compiled to CSS:
```css
@media (min-width: 992px) {
    .has-sidebar-left .app {
        margin-left: 0;
    }
    .sidebar-left-in .app {
        margin-left: 300px;
    }
}
```
Your mileage may vary.
@mcasimir styles seems sometimes very hardcoded, I had to place some workarounds too working with MAUI, wondering if they can be further modularized or customizable, particularly in behaviors like these...
