### ISSUE TITLE
scrollableContent form input/textarea style: {pointer-events: none;}

### ISSUE THREAD

**Issue by maqic** [mcasimir/mobile-angular-ui#360]
browser: google chrome v50.0.2661.94 (64-bit) **device mode** iPhone 6
desc: click on `scrollable-content` div cause style: {pointer-events: none;} on input or textarea element

```javascript
  // overthrow.support === 'none'
  if (overthrow.support !== 'native') {
    element.addClass('overthrow');
    overthrow.forget();
    overthrow.set();
  }
```

why?

**Comment by maqic** [comment]
i suggest to remove overthrow.js

or set

```css
    input, textarea {
      pointer-events: auto !important;
    }
```
